# Generated by Django 3.1.7 on 2021-02-25 08:01

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, verbose_name='이메일')),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='매니저')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='관리자')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='아이디')),
                ('name', models.CharField(max_length=40, verbose_name='이름')),
                ('post_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='우편번호')),
                ('address1', models.CharField(blank=True, max_length=150, null=True, verbose_name='주소1')),
                ('address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='주소2')),
                ('phone', models.CharField(max_length=50, verbose_name='전화번호')),
                ('status', models.CharField(choices=[('act', '사용중'), ('del', '탈퇴'), ('rest', '휴면'), ('stop', '중지')], max_length=10, verbose_name='사용자상태')),
                ('sms_receive_yn', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=1, verbose_name='SMS 수신여부')),
                ('email_receive_yn', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=1, verbose_name='Email 수신여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='로그인')),
                ('password_at', models.DateTimeField(blank=True, null=True, verbose_name='비밀번호 수정일')),
            ],
            options={
                'verbose_name': '회원정보',
                'verbose_name_plural': '회원정보',
                'ordering': ('-id',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
