# Generated by Django 3.1.7 on 2021-02-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='CatkinUser',
        ),
        migrations.AlterModelManagers(
            name='catkinuser',
            managers=[
            ],
        ),
    ]
