# Generated by Django 3.1.7 on 2021-03-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210225_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catkinuser',
            name='email_receive_yn',
        ),
        migrations.RemoveField(
            model_name='catkinuser',
            name='sms_receive_yn',
        ),
    ]
